// Regenerates server/cv/content.ts from the portfolio's résumé data, the one source of truth
// (../spidey-portfolio/scripts/cv/content.mjs). Run `npm run cv:sync` after editing the CV there,
// so the fitted CV and the agents' profile never drift from the PDFs on erikkarasek.cz.
import { readFileSync, writeFileSync } from 'node:fs'

const SOURCE = new URL('../../spidey-portfolio/scripts/cv/content.mjs', import.meta.url)
const TARGET = new URL('../server/cv/content.ts', import.meta.url)

const src = readFileSync(SOURCE, 'utf8')
const phone = src.match(/export const PHONE = '([^']+)'/)?.[1]
const body = src.slice(src.indexOf('const shared'))
const photoLine = /^ {2}photo: 'public\/img\/me-cv\.jpg',.*$/m
if (!phone || !photoLine.test(body)) throw new Error('The portfolio CV changed shape; update scripts/sync-cv.mjs.')

writeFileSync(
  TARGET,
  `// Generated by scripts/sync-cv.mjs from spidey-portfolio/scripts/cv/content.mjs, which also renders
// the general PDFs on erikkarasek.cz. Edit the CV there, then run \`npm run cv:sync\`. It feeds the
// tailored CV (server/cv/tailor.ts) and the profile the agents score against (server/agent/profile.ts).

// Already on the public résumé PDFs and in the portfolio repo.
export const PHONE = '${phone}'

${body.replace(photoLine, "  // Served by the portfolio; the head-only crop of the hero shot.\n  photo: 'https://erikkarasek.cz/img/me-cv.jpg',").trimEnd()}

export type Cv = typeof cv.cs
export type CvLang = keyof typeof cv
`,
)
console.log('server/cv/content.ts synced from the portfolio')
